# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-05 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='password',
            field=models.CharField(default=True, max_length=50),
        ),
    ]
