# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-05 03:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0002_user_details_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='password',
            field=models.CharField(default=50, max_length=50),
        ),
    ]
