# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-05 03:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20190705_0322'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
