# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-05 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_auto_20190705_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='password',
            field=models.CharField(default='0000000', max_length=50),
        ),
    ]
