# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-05 05:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_auto_20190705_0329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='user_details',
            name='last_name',
        ),
        migrations.AddField(
            model_name='user_details',
            name='User_name',
            field=models.CharField(default='0000000', max_length=50),
        ),
    ]
