# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-05 06:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0006_auto_20190705_0546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_details',
            old_name='User_name',
            new_name='user_name',
        ),
    ]
