# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-06 03:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_auto_20190705_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='confirm_password',
            field=models.CharField(default='0000000', max_length=50),
        ),
        migrations.AddField(
            model_name='user_details',
            name='contact_number',
            field=models.CharField(default='0000000', max_length=50),
        ),
    ]
