# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-06 03:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0008_auto_20190706_0301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_details',
            name='contact_number',
        ),
        migrations.AlterField(
            model_name='user_details',
            name='email_id',
            field=models.CharField(max_length=50),
        ),
    ]
