# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-06 03:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0009_auto_20190706_0326'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_details',
            name='contact_number',
            field=models.IntegerField(default='0000000'),
        ),
    ]
