# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-07-08 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0012_user_details_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_details',
            name='contact_number',
            field=models.CharField(default='0000000', max_length=50),
        ),
    ]
